compile:
	neo-go contract compile -i ./entrypoint/main.go -c ./entrypoint/main.yml -m ./entrypoint/contract.manifest.json
	neo-go contract compile -i ./paymaster/main.go -c ./paymaster/main.yml -m ./paymaster/contract.manifest.json


